### ISSUE TITLE
allow queries to come from file

### ISSUE THREAD

**Issue by goertzenlr** [fulcrumgenomics/fqgrep#11]
a "-f" option that allows query or queries from a file, incl. fasta format, concatenate all output.  assumes "ref seq optional" enhancement

**Comment by nh13** [comment]
I'd propose we change `fqgrep` in the following way:

Replace the `-r` and `-a` options with a `-q` option.  The `-q` can take one or more arguments.  Each argument can either be a sequence to search, or a file that contains sequences to search, one-per line (could add support for FASTA/FASTQ format later).

Change the FASTQ output to have one FASTQ per input sequence, and a "ALL" FASTQ for reads that match _all_ the input sequences.

Change the stats output to have a row per input sequence, with a column counting the # of reads that match that sequence.  Include an "ALL" row to count the # of reads that match _all_ the sequences.  We could instead include a pairwise matrix (how many match every possible pair of input sequences), but that seems overkill.

This would be a major change.




 

1. Add an option `-f` that can take one or more queries from a file.

**Comment by tfenne** [comment]
My 2c would be to actually mirror `grep` fairly closely and have it take positional args(!) for as many query strings as you want, and also a `-f <file>` (as you say, for now one pattern per line, could take fastq/fasta later).  As you say, get rid of the `-r` and `-a` options.  And perhaps add an option for also querying for the reverse complement of patterns to make that transparent.

**Comment by goertzenlr** [comment]
I like these ideas.  "-q" approach makes it more self contained vs. external loop setup that feeds positional params.  either way this change preserves multiple use cases e.g. original find all reads around a specific polymorphism of interest and split them, but also simply find all reads related to this broader sequence and lump them.  And it is really fast hence highly useful either way.   thanks!

**Comment by nh13** [comment]
Fixed in #13 with `-f <file>`
