### ISSUE TITLE
program name

### ISSUE THREAD

**Issue by darked89** [fulcrumgenomics/fqgrep#14]
Hello,

This is of minor importance, but just in case you have been not aware of this: there is a existing software with exactly the same name:

https://github.com/indraniel/fqgrep

and with the +/- same functionality. It is great to have a new take on the grepping reads in a fastq files. Still, adding some prefix/suffix (rfqgrep? fqgrepfg?) may help with a confusion. 

Since the older fqgrep is hardly maintained I will happily switch to your tool after a bit of testing.

Hope it helps.

Darek Kedra

**Comment by nh13** [comment]
Thanks for the link. We have a major update incoming: https://github.com/fulcrumgenomics/fqgrep/pull/13 that will make it very similar to grep itself. Also, the motivation of this project was for me to learn rust, so I hope people also find this tool useful.
